### ISSUE TITLE
Add Javadoc 

### ISSUE THREAD

**Issue by riteshakya037** [riteshakya037/RatioLayouts#1]
Add a detailed javadoc in accordance to http://www.oracle.com/technetwork/articles/java/index-137868.html

**Comment by marti1125** [comment]
I could help you 😄 but I need a list of method needs add javadoc please and where 👍

**Comment by riteshakya037** [comment]
@marti1125 Hey there thanks for the response. To be honest you can start anywhere you want, the method names should be explanatory. If you have any other confusions let me know. 
Thanks
